<?php
// Start the session to access session variables
session_start();

// Check if the user is logged in by checking for the 'user_id' session variable
if (!isset($_SESSION['user_id'])) {
    // If not logged in, redirect to index.phtml
    header("Location: index.phtml");
    exit();
}

// Store the user_id for later use in the page
$user_id = $_SESSION['user_id'];
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="css/styles.css">
    <link rel="stylesheet" href="css/mediaQuerries.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">
</head>
<body>
    <section class="page">
        <div class="headerContainer">
            <header>
                <nav class="desktopNav">
                  <div class="navLogo">
                    <a href="index.phtml" class="logo">PeakFit</a>
                  </div> 
    
                  <ul>
                    <li><a href="#services">Υπηρεσίες</a></li>
                    <li><a href="#about">Σχετικά</a></li>
                    <li><a href="#news">Νέα</a></li>
                    <li><a href="#">Ραντεβού</a></li>
                  </ul>
                  <div class="account accountRes">
                    <button class="signin"><img src="assets/icons/user.png" alt=""></button>
                  </div>
                </nav>
    
    
                <nav class="mobileNav">
                    <div class="navLogo">
                      <a href="#" class="logo">PeakFit</a>
                    </div> 
      
                    
                    <div class="account">
                        <div class="signin ham-menu">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </div>
                  </nav>
    
                  <div class="off-screen-menu">
                    <ul>
                        <li><a href="#header">Home</a></li>
                        <li><a href="#about">About</a></li>
                        <li><a href="#portfolio">Contact</a></li>
                        <li><a href="#contact">Reservation</a></li>
                    </ul>
                </div>
                
                

            </header>
        </div>
        <div class="mainContent">
        <input type="hidden" id="userIdInput" value="<?php echo htmlspecialchars($user_id); ?>" />

            <div class="reservation">
                <div class="optionsData">
                    <div class="options">
                        <h3>Επιλογές <button class="filterToggle"><i class="fa-solid fa-xmark"></i></button></h3>
                        <div class="filter-tab">
                            <div class="filter-category">
                                <button class="dropdown-toggle catMain">Ατομικά <img class="chevIcon" src="assets/icons/whiteChevDown.png" alt=""></button>
                                <ul class="dropdown-menu">
                                <button type="button" onclick="renderReservations('weights')">
                                    <img src="assets/icons/dumbellWhite.png" alt="">Ελεύθερα Βάρη
                                </button>                                    
                                <li><button onclick="renderReservations('cardio')" type="button" ><img src="assets/icons/heartWhite.png" alt="">Cardio</button></li>
                                    <li><button onclick="renderReservations('pilates')" type="button"><img src="assets/icons/pilatesWhite.png" alt="">Pilates</button></li>
                                </ul>
                            </div>
                            <div class="filter-category">
                                <button class="dropdown-toggle catMain">Ομαδικά <img class="chevIcon" src="assets/icons/whiteChevDown.png" alt=""></button></button>
                                <ul class="dropdown-menu">
                                    <li><button type="button" onclick="renderReservations('yoga')"><img src="assets/icons/yogaWhite.png" alt=""> Yoga</button></li>
                                    <li><button type="button" onclick="renderReservations('kick boxing')"><img src="assets/icons/kickboxWhite.png" alt=""> Kick Boxing</button></li>
                                    <li><button type="button" onclick="renderReservations('trx')"><img src="assets/icons/trxWhite.png" alt="">TRX</button></li>
                                </ul>
                            </div>
                        </div>
                        <button class="dropdown-toggle catMain">Ιστορικό</button>
                    </div>
                    <div class="sqlData">
                        <h3 class="title"><button id="filterIcon" class="filterToggle none"><i class="fa-solid fa-bars"></i></button>Ελεύθερα Βάρη</h3>
                        <input type="hidden" id="serviceName" value="weights">
                        <div class="dateRefresh">
                            <div class="dateChecker">
                                <p>Επιλογή Ημερομηνίας <input id="datePicker" type="date"></p>
                            </div>
                            <button id="checkButton"><img src="assets/icons/refresh.png" alt="">Έλεγχος</button>
                        </div>
                        <div class="timePicker">
                            <div class="group">
                                <div class="timeSlot">
                                    <div class="slotTime">
                                        <p>07:00 - 08:00</p>
                                        <p>10/12/2024</p>
                                    </div>
                                    <div class="slotBook">
                                        <p>Θέσεις: 12/64</p>
                                        <button>Κράτηση</button>
                                    </div>
                                </div>
                                <div class="timeSlot">
                                    <div class="slotTime">
                                        <p>07:00 - 08:00</p>
                                        <p>10/12/2024</p>
                                    </div>
                                    <div class="slotBook">
                                        <p>Θέσεις: 12/64</p>
                                        <button>Κράτηση</button>
                                    </div>
                                </div>
                                <div class="timeSlot">
                                    <div class="slotTime">
                                        <p>07:00 - 08:00</p>
                                        <p>10/12/2024</p>
                                    </div>
                                    <div class="slotBook">
                                        <p>Θέσεις: 12/64</p>
                                        <button>Κράτηση</button>
                                    </div>
                                </div>
                                <div class="timeSlot">
                                    <div class="slotTime">
                                        <p>07:00 - 08:00</p>
                                        <p>10/12/2024</p>
                                    </div>
                                    <div class="slotBook">
                                        <p>Θέσεις: 12/64</p>
                                        <button>Κράτηση</button>
                                    </div>
                                </div>
                                <div class="timeSlot">
                                    <div class="slotTime">
                                        <p>07:00 - 08:00</p>
                                        <p>10/12/2024</p>
                                    </div>
                                    <div class="slotBook">
                                        <p>Θέσεις: 12/64</p>
                                        <button>Κράτηση</button>
                                    </div>
                                </div>
                                <div class="timeSlot">
                                    <div class="slotTime">
                                        <p>07:00 - 08:00</p>
                                        <p>10/12/2024</p>
                                    </div>
                                    <div class="slotBook">
                                        <p>Θέσεις: 12/64</p>
                                        <button>Κράτηση</button>
                                    </div>
                                </div>
                                <div class="timeSlot">
                                    <div class="slotTime">
                                        <p>07:00 - 08:00</p>
                                        <p>10/12/2024</p>
                                    </div>
                                    <div class="slotBook">
                                        <p>Θέσεις: 12/64</p>
                                        <button>Κράτηση</button>
                                    </div>
                                </div>
                                <div class="timeSlot">
                                    <div class="slotTime">
                                        <p>07:00 - 08:00</p>
                                        <p>10/12/2024</p>
                                    </div>
                                    <div class="slotBook">
                                        <p>Θέσεις: 12/64</p>
                                        <button>Κράτηση</button>
                                    </div>
                                </div>
                            </div>
                            <span class="groupBorder"></span>
                            <div class="group">
                                <div class="timeSlot">
                                    <div class="slotTime">
                                        <p>07:00 - 08:00</p>
                                        <p>10/12/2024</p>
                                    </div>
                                    <div class="slotBook">
                                        <p>Θέσεις: 12/64</p>
                                        <button>Κράτηση</button>
                                    </div>
                                </div>
                                <div class="timeSlot">
                                    <div class="slotTime">
                                        <p>07:00 - 08:00</p>
                                        <p>10/12/2024</p>
                                    </div>
                                    <div class="slotBook">
                                        <p>Θέσεις: 12/64</p>
                                        <button>Κράτηση</button>
                                    </div>
                                </div>
                                <div class="timeSlot">
                                    <div class="slotTime">
                                        <p>07:00 - 08:00</p>
                                        <p>10/12/2024</p>
                                    </div>
                                    <div class="slotBook">
                                        <p>Θέσεις: 12/64</p>
                                        <button>Κράτηση</button>
                                    </div>
                                </div>
                                <div class="timeSlot">
                                    <div class="slotTime">
                                        <p>07:00 - 08:00</p>
                                        <p>10/12/2024</p>
                                    </div>
                                    <div class="slotBook">
                                        <p>Θέσεις: 12/64</p>
                                        <button>Κράτηση</button>
                                    </div>
                                </div>
                                <div class="timeSlot">
                                    <div class="slotTime">
                                        <p>07:00 - 08:00</p>
                                        <p>10/12/2024</p>
                                    </div>
                                    <div class="slotBook">
                                        <p>Θέσεις: 12/64</p>
                                        <button>Κράτηση</button>
                                    </div>
                                </div>
                                <div class="timeSlot">
                                    <div class="slotTime">
                                        <p>07:00 - 08:00</p>
                                        <p>10/12/2024</p>
                                    </div>
                                    <div class="slotBook">
                                        <p>Θέσεις: 12/64</p>
                                        <button>Κράτηση</button>
                                    </div>
                                </div>
                                <div class="timeSlot">
                                    <div class="slotTime">
                                        <p>07:00 - 08:00</p>
                                        <p>10/12/2024</p>
                                    </div>
                                    <div class="slotBook">
                                        <p>Θέσεις: 12/64</p>
                                        <button>Κράτηση</button>
                                    </div>
                                </div>
                                <div class="timeSlot">
                                    <div class="slotTime">
                                        <p>07:00 - 08:00</p>
                                        <p>10/12/2024</p>
                                    </div>
                                    <div class="slotBook">
                                        <p>Θέσεις: 12/64</p>
                                        <button>Κράτηση</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    
                    </div>
                </div>
            </div>
        </div>
    </section>
   

    <script src="javaScript/reservationScripts.js"></script>
    <script src="javaScript/reservationsDataFetching.js"></script>
</body>
</html>

